# Generated by cpputils-cmake.
include /Users/Rayiner/Projects/ccpoc/build/CMakeFiles/ccpoc.dir/flags.make
.PHONY: check-syntax
check-syntax:
	${CC} -o /dev/null ${C_FLAGS} ${C_DEFINES} ${C_INCLUDES}  -S ${CHK_SOURCES}